cluster := csharp
all:
	if ! [ -x "$$(command -v kind)" ]; then \
		curl -sLo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64; \
		chmod +x ./kind; \
		sudo mv ./kind /usr/local/bin/kind; \
	fi
	kind create cluster --name $(cluster) --config=.github/workflows/assets/kind.yaml

clean:
	kind delete clusters $(cluster)
